Feature/notification
peaksoft-school/gift-list-js10 pull request #28
Opened 2023-10-25 18:43 UTC by Satybaldyeva

2023-10-26 10:42 UTC, NuraiymMamatova commented on src/utils/helpers/constants.js
> +import { SamatOkenov, Ellipse, Aida, Askar } from '../../assets'
You should to add images into index.js in assets or just replace image components with url.
Like this: 
export const notifications = [
   {
      name: 'Самат Окенов',
      id: '1',
      image: 'https://t3.ftcdn.net/jpg/02/43/12/34/360_F_243123463_zTooub557xEWABDLk0jJklDyLSGl2jrr.jpg',
      description: ' добавил желаемый подарок',
      date: '25.05.2022',
   },
   {
      name: 'Название подарка ',
      id: '2',
      image: 'https://t4.ftcdn.net/jpg/03/83/25/83/360_F_383258331_D8imaEMl8Q3lf7EKU2Pi78Cn0R7KkW9o.jpg',
      description: ' было забронировано анонимным пользователем',
      date: '25.05.2022',
   },
   {
      name: 'Название подарка',
      id: '3',
      image: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      description: ' было забронировано Аида Мамытбек',
      date: '25.05.2022',
   },
   {
      name: 'Аскар Оморов ',
      id: '4',
      image: 'https://images.healthshots.com/healthshots/en/uploads/2020/12/08182549/positive-person.jpg',
      description: 'отправил запрос в друзья',
      date: '25.05.2022',
   },
]

2023-10-30 07:17 UTC, NuraiymMamatova commented on .eslintrc.json
> +      "no-nested-ternary": "off"
delete rule "no-nested-ternary": "off"

2023-10-30 07:17 UTC, NuraiymMamatova commented on src/components/Notification.jsx
> +   const [state, setSate] = useState(false)
rename this state please.

2023-10-31 04:08 UTC, NuraiymMamatova commented on src/components/Notification.jsx
> +const Description = styled('div')({})
You don't give the styles here.

2023-10-31 05:15 UTC, NuraiymMamatova approved these changes

2023-11-06 05:42 UTC, AziatAbd requested changes

2023-11-06 05:42 UTC, AziatAbd commented on src/components/Notification.jsx
> +         {isOpenNotifications ? (
backdrop басылганда жабылып калыш керек

2023-11-06 05:42 UTC, AziatAbd commented on src/components/Notification.jsx
> +                  })}
![image](https://github.com/peaksoft-school/gift-list-js10/assets/115453436/6cddb98b-1e9f-4bf6-a585-af322af00f55)
если массив пустой, то покажите какой-нибудь текст что здесь нету уведомлении

2023-11-06 05:42 UTC, AziatAbd commented on src/components/Notification.jsx
> +                        </List>
![image](https://github.com/peaksoft-school/gift-list-js10/assets/115453436/08eb48d9-ab9e-479f-93d0-ac518ff0219d)
active болгондо date астында калып кетиптир. Текст 2 строкадан ашып кетпесин ашып кетсе '...' коюп коюн ордуна

2023-11-08 05:03 UTC, merged